global using Application.Domain.Entities;
global using Application.Features.Clients.Queries;
global using Application.Infrastructure.IoC.CQRS.Profiles;
global using Application.Persistence.Context;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;